[package]
name = "rise-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rise_core"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "rise-core"
path = "src/main.rs"

[dependencies]
sha2 = "0.10"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
